- name: Meson Build
  # You may pin to the exact commit or the version.
  # uses: BSFishy/meson-build@656b2a360964b249ac82905a52018921e01d875b
  uses: BSFishy/meson-build@v1.0.3
  with:
    # The action to run
    action: build
    # The directory to build the project to
    directory: out
    # Additional options to pass to Meson during setup
    setup-options: ""
    # Additional options to pass to Meson
    options: ""
    # The version of Meson to use
    meson-version: "0.53.2"
    # The version of Ninja to use
    ninja-version: "1.9.0.post1"
    # The version of gcovr to use (If doing coverage)
    gcovr-version: "4.2"