name: Meson Build

on:
    push:
        branches:
            - actions_github
        tags:
            - v*
            - "v*.*"

jobs:
    build:
        name: Build Project
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
        - name: Install and build with Meson
          run: |
            pip install meson ninja
            meson setup out
            meson compile -C out
        - name: Run tests
          run: |
            echo -e "1\n32\n16\n8\n2\n3\n4\n185\n5\n15\n0" | ./out/traductor entrada.txt
        #- name: Upload traductor and entrada.txt
          #uses: actions/upload-artifact@v4
          #with:
            #name: build-artifacts
            #path: |
                #out/traductor
                #entrada.txt
    upload:
      # Upload to releases
        name: Upload Artifact to Releases
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          # Genera el archivo CHANGELOG
          - name: Generate Binaries Again
            uses: actions/setup-python@v5
          - name: Install and build with Meson
            run: |
              pip install meson ninja
              meson setup out
              meson compile -C out
          - name: Generate Changelog
            run: echo "# Ultimos Cambios Guardados" > ${{ github.workspace }}-CHANGELOG.txt
          # Publica el release
          - name: Release
            uses: softprops/action-gh-release@v2
            #if: startsWith(github.ref, 'refs/tags/')
            with:
              body_path: ${{ github.workspace }}-CHANGELOG.txt
              repository: my_gh_org/my_gh_repo
              token: ${{ secrets.GITHUB_TOKEN }}
              files: |
                out/traductor
                entrada.txt

             